# Generated by Django 2.2.12 on 2020-06-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costs.Customer', verbose_name='Driftes av')),
            ],
            options={
                'verbose_name': 'kunde',
                'verbose_name_plural': 'kunder',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Ansvar')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.Customer')),
            ],
            options={
                'verbose_name': 'ansvar',
                'verbose_name_plural': 'ansvar',
                'ordering': ['name'],
                'unique_together': {('number', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tjeneste')),
                ('price', models.IntegerField(verbose_name='Pris')),
            ],
            options={
                'verbose_name': 'tjeneste',
                'verbose_name_plural': 'tjenester',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tjenestetype',
                'verbose_name_plural': 'tjenestetyper',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Ressursnummer')),
                ('ad_user', models.CharField(max_length=50, verbose_name='Brukernavn AD')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='Epostadresse')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.Department')),
            ],
            options={
                'verbose_name': 'bruker',
                'verbose_name_plural': 'brukere',
                'unique_together': {('number', 'ad_user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('dns_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS-navn')),
                ('dn', models.CharField(max_length=200, verbose_name='DN')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beskrivelse')),
                ('last_logon', models.DateTimeField(blank=True, null=True, verbose_name='Sist aktiv')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='costs.Customer', verbose_name='Kunde')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='costs.Product', verbose_name='Tjeneste')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servere',
                'unique_together': {('name', 'customer')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.ProductType'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('department_prefix', models.IntegerField(verbose_name='Første siffer i ansvar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='costs.Customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektorer',
                'unique_together': {('department_prefix', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Applikasjonsnavn')),
                ('vendor', models.CharField(max_length=100, verbose_name='Leverandør')),
                ('cloud', models.BooleanField(verbose_name='Skytjeneste')),
                ('licence_cost', models.IntegerField(blank=True, null=True, verbose_name='Lisenskostnad')),
                ('internal_hours', models.IntegerField(blank=True, null=True, verbose_name='Applikasjonsdrift timer pr mnd')),
                ('external_cost', models.IntegerField(blank=True, null=True, verbose_name='Konsulentkostnad')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='costs.Customer', verbose_name='Kunde')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costs.Department', verbose_name='Ansvar')),
                ('integrations', models.ManyToManyField(blank=True, related_name='_application_integrations_+', to='costs.Application', verbose_name='Integrasjoner')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible', to='costs.User', verbose_name='Systemansvarlig')),
                ('servers', models.ManyToManyField(blank=True, related_name='applications', to='costs.Server', verbose_name='Servere')),
                ('super_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='super_user', to='costs.User', verbose_name='Superbruker')),
            ],
            options={
                'verbose_name': 'applikasjon',
                'verbose_name_plural': 'applikasjoner',
                'ordering': ['customer', 'name'],
                'unique_together': {('customer', 'name', 'department')},
            },
        ),
    ]
