# Generated by Django 2.2.12 on 2020-06-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_productdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': 'Sektor', 'verbose_name_plural': 'Sektorer'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'bruker', 'verbose_name_plural': 'brukere'},
        ),
    ]
