# Generated by Django 2.2.12 on 2020-06-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_auto_20200619_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='sector_dep', to='costs.Department', verbose_name='Ansvar'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'customer')},
        ),
        migrations.RemoveField(
            model_name='sector',
            name='department_prefix',
        ),
    ]
