# Generated by Django 2.2.12 on 2020-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_auto_20200619_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='dn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DN'),
        ),
    ]
