# Generated by Django 2.2.12 on 2020-07-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_server_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['customer', 'name'], 'verbose_name': 'server', 'verbose_name_plural': 'servere'},
        ),
    ]
