# Generated by Django 2.2.12 on 2020-07-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_server_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Pris per måned'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.ProductType', verbose_name='Tjenestetype'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Tjenestetype'),
        ),
    ]
