# Generated by Django 2.2.12 on 2020-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0008_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DN'),
        ),
    ]
