# Generated by Django 3.1 on 2020-08-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_user_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logon',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sist aktiv'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='costs.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='DN'),
        ),
    ]
