# Generated by Django 3.1 on 2020-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0011_department_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='product_groups', to='costs.Product', verbose_name='Tjenester')),
            ],
            options={
                'verbose_name': 'Tjenestegruppe',
                'verbose_name_plural': 'Tjenestegrupper',
                'ordering': ['name'],
            },
        ),
    ]
