# Generated by Django 3.1 on 2020-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_import', '0005_directory_related_name'),
        ('costs', '0013_user_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_update',
        ),
        migrations.AddField(
            model_name='customer',
            name='ad_directories',
            field=models.ManyToManyField(to='ad_import.Directory'),
        ),
        migrations.AddField(
            model_name='server',
            name='ad_object',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad_import.server', verbose_name='AD'),
        ),
        migrations.AddField(
            model_name='user',
            name='ad_object',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ad_import.user', verbose_name='AD'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='costs.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Epostadresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Ressursnummer'),
        ),
    ]
