# Generated by Django 3.1.1 on 2020-10-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_import', '0006_manager_set_null'),
        ('costs', '0015_costdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ad_object',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_import.server', verbose_name='AD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ad_object',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ad_import.user', verbose_name='AD'),
        ),
    ]
