# Generated by Django 3.1.1 on 2020-10-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0017_server_ip_ad_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Type', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivelse')),
            ],
            options={'verbose_name': 'servertype', 'verbose_name_plural': 'servertyper'},
        ),

        migrations.AddField(
            model_name='server',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servertype', to='costs.servertype'),
        ),
    ]
