# Generated by Django 3.1.1 on 2020-10-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0018_server_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='costs.sector', verbose_name='Sektor'),
        ),
    ]
