# Generated by Django 3.1.1 on 2020-10-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0001_initial'),
        ('costs', '0021_labels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costdistribution',
            unique_together={('application', 'account', 'cost_center', 'function')},
        ),
        migrations.RemoveField(
            model_name='costdistribution',
            name='company',
        ),
    ]
