# Generated by Django 3.1.1 on 2020-10-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_import', '0006_manager_set_null'),
        ('costs', '0022_costdistribution_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='navn')),
                ('distinguishedName', models.CharField(blank=True, max_length=300, null=True, verbose_name='DN')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='merke')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='modell')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='serienummer')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='brukernavn')),
                ('user_domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='brukerdomene')),
                ('ad_object', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstation', to='ad_import.workstation', verbose_name='AD')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='costs.customer', verbose_name='kunde')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='costs.user', verbose_name='bruker')),
            ],
            options={
                'verbose_name': 'arbeidsstasjon',
                'verbose_name_plural': 'arbeidsstasjoner',
                'ordering': ['customer', 'model'],
            },
        ),
    ]
