# Generated by Django 3.1.1 on 2020-11-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0023_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='users', to='costs.Product', verbose_name='tjenester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='costs.customer', verbose_name='Kunde'),
        ),
    ]
