# Generated by Django 3.1.1 on 2020-11-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0002_organisation_set_null'),
        ('costs', '0024_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='account',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='konto'),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_info.costcenter', verbose_name='ansvar'),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_info.function', verbose_name='funksjon'),
        ),
    ]
