# Generated by Django 3.1.5 on 2021-01-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0025_product_delivery_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='last_logon',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Siste pålogging'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='leased',
            field=models.BooleanField(default=False, verbose_name='leid'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='costs.user', verbose_name='eier'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='costs.product', verbose_name='tjeneste'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='pus_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='PureService ID'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations_user', to='costs.user', verbose_name='siste bruker'),
        ),
    ]
