# Generated by Django 3.1.5 on 2021-01-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0004_employment_sequenceref'),
        ('costs', '0026_workstation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='cost_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='employee_info.costcenter', verbose_name='ansvar'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='function',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='employee_info.function', verbose_name='funksjon'),
        ),
    ]
