# Generated by Django 3.1.5 on 2021-01-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0005_function_company_optional'),
        ('costs', '0029_user_pus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisations', models.ManyToManyField(related_name='product_mapping', to='employee_info.Organisation', verbose_name='organisasjonsenheter')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='costs.product', verbose_name='tjeneste')),
            ],
        ),
    ]
