# Generated by Django 3.1.1 on 2020-11-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0023_workstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='dato')),
                ('locked', models.BooleanField(default=False, verbose_name='låst')),
                ('exported', models.BooleanField(default=False, verbose_name='eksportert')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='costs.customer')),
            ],
            options={
                'verbose_name': 'faktura',
                'verbose_name_plural': 'fakturaer',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=6, verbose_name='konto')),
                ('cost_center', models.CharField(max_length=4, verbose_name='ansvar')),
                ('function', models.IntegerField(verbose_name='funksjon')),
                ('dim3', models.CharField(blank=True, max_length=8, null=True, verbose_name='anlegg/ressurs')),
                ('dim4', models.CharField(blank=True, max_length=8, null=True, verbose_name='prosjekt')),
                ('dim5', models.CharField(blank=True, max_length=8, null=True, verbose_name='dimensjon 5')),
                ('dim6', models.CharField(blank=True, max_length=8, null=True, verbose_name='dimensjon 6')),
                ('tax', models.CharField(blank=True, default='06', max_length=2, verbose_name='avgiftskode')),
                ('text', models.CharField(max_length=200, verbose_name='tekst')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='beløp')),
                ('tax_code', models.CharField(default='06', max_length=3, verbose_name='avgiftskode')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'fakturalinje',
                'verbose_name_plural': 'fakturalinjer',
                'unique_together': {('invoice', 'account', 'cost_center', 'function', 'text', 'amount')},
            },
        ),
    ]
